'use client';
import {tablePrice,selectionTotal} from '@/data/cinema-pricing';
import {cinemaHallConfig} from '@/data/cinema-hall';

import {useState,useEffect,useCallback,useRef} from 'react';
import {type MovieEvent,dateLabel,money,isPast} from '@/data/cinema';
import {type Seat,seatLabel} from '@/data/cinema-hall';
import {type CinemaOrder} from '@/lib/cinema/orders';
import {CinemaHall} from './hall';
import {VenueView} from './venue-view';
import {type CinemaViewId} from '@/data/cinema-views';
export function CinemaAdmin(){
 const [onlineSalesReady,setOnlineSalesReady]=useState(false),[savedIds,setSavedIds]=useState<string[]>([]);
 const [key,setKey]=useState(''),[logged,setLogged]=useState(false),[events,setEvents]=useState<MovieEvent[]>([]),[event,setEvent]=useState<MovieEvent|null>(null),[orders,setOrders]=useState<CinemaOrder[]>([]),[seats,setSeats]=useState<Seat[]>([]),[selected,setSelected]=useState<string[]>([]),[view,setView]=useState<CinemaViewId|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[phone,setPhone]=useState('');const requestKey=useRef('');
 const api=useCallback(async(path:string,body?:unknown)=>{const r=await fetch('/api/cinema/admin'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.message||'Ошибка запроса');return d;},[key]);
 const refresh=useCallback(async(id:string)=>{const [d,r]=await Promise.all([api('?eventId='+encodeURIComponent(id)),fetch('/api/cinema/events/'+encodeURIComponent(id)+'/seats',{cache:'no-store'})]);if(!r.ok)throw Error('Не удалось загрузить места');setOnlineSalesReady(Boolean(d.onlineSalesReady));setOrders(d.orders);setSeats((await r.json()).seats);},[api]);
 useEffect(()=>{if(!logged||!event)return;const id=event.id;void refresh(id).catch(e=>setError(e.message));const t=setInterval(()=>void refresh(id).catch(e=>setError(e.message)),5000);return()=>clearInterval(t);},[logged,event?.id,refresh]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const savedEvent=events.find(e=>e.id===event?.id)||event;
 const eventDirty=Boolean(event&&savedEvent&&JSON.stringify(event)!==JSON.stringify(savedEvent));
 const pricesDirty=Boolean(event&&savedEvent&&(event.pricePerSeat!==savedEvent.pricePerSeat||JSON.stringify(event.tablePrices||{})!==JSON.stringify(savedEvent.tablePrices||{})));
 const change=(field:keyof MovieEvent,value:unknown)=>setEvent(e=>e?{...e,[field]:value}:e);
 if(!logged)return <main className="cinema-container legal-page"><h1>Вход администратора</h1><p>Введите ключ доступа, установленный на сервере. Ключ не сохраняется в браузере.</p><form className="customer-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const d=await api('');setOnlineSalesReady(Boolean(d.onlineSalesReady));setSavedIds(d.events.map((e:MovieEvent)=>e.id));setEvents(d.events);setEvent(d.events[0]||null);setLogged(true);});}}><label>Ключ доступа<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required minLength={32}/></label><button disabled={busy}>Войти</button>{error&&<p role="alert">{error}</p>}</form></main>;
 return <main className="cinema-container admin-page"><div className="admin-toolbar"><h1>Киноужины</h1><button onClick={()=>{setLogged(false);setKey('');setOrders([]);}}>Выйти</button></div><p>Изменения сохраняются в базе и видны гостям. Онлайн-продажи включаются отдельно после подключения оплаты.</p>{error&&<p className="cinema-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <div className="admin-toolbar"><select aria-label="Киноужин" value={event?.id||''} onChange={e=>{setEvent(events.find(x=>x.id===e.target.value)||null);setSelected([]);requestKey.current='';}}>{events.map(e=><option key={e.id} value={e.id}>{dateLabel(e)} · {e.title}</option>)}</select><button disabled={busy} onClick={()=>{const base=event||events[0];if(!base)return;const id='event-'+crypto.randomUUID();const e={...base,id,slug:id,title:'Новый киноужин',bookingPaused:true,saleStatus:'closed' as const};setEvents(old=>[...old,e]);setEvent(e);setSelected([]);}}>Добавить вечер</button></div>
 {event&&<><section className="admin-editor"><h2>Бронирование и оплата</h2><p role="status">{isPast(savedEvent!)?'Сеанс начался или завершён — новые брони закрыты':savedEvent?.bookingPaused?'Бронирование остановлено':onlineSalesReady?'Бронирование и онлайн-оплата открыты':'Онлайн-оплата не настроена'}</p><div className="admin-toolbar"><button disabled={busy||eventDirty||!savedIds.includes(event.id)||Boolean(savedEvent?.bookingPaused)} onClick={()=>void run(async()=>{const d=await api('/sales',{id:event.id,enabled:false});setEvent(d.event);setEvents(old=>old.map(x=>x.id===d.event.id?d.event:x));setMessage('Бронирование остановлено. Можно готовить следующий вечер.');})}>Остановить бронирование</button><button disabled={busy||eventDirty||!savedIds.includes(event.id)||!onlineSalesReady||isPast(savedEvent!)||(!savedEvent?.bookingPaused&&onlineSalesReady)} onClick={()=>void run(async()=>{const d=await api('/sales',{id:event.id,enabled:true});setEvent(d.event);setEvents(old=>old.map(x=>x.id===d.event.id?d.event:x));setMessage('Бронирование и онлайн-оплата возобновлены.');})}>Возобновить бронирование и оплату</button></div>{eventDirty||!savedIds.includes(event.id)?<p>Сначала сохраните изменения афиши.</p>:null}{!onlineSalesReady&&<p>Для онлайн-оплаты требуется настроенная ЮKassa и CINEMA_ONLINE_SALES=true на VPS.</p>}<p>Новые брони автоматически закрываются с началом сеанса. Для следующего показа нажмите «Добавить вечер»: он создаётся с закрытым бронированием и свободными местами. Заполните афишу, сохраните и откройте продажи.</p></section><form className="customer-form admin-editor" onSubmit={e=>{e.preventDefault();void run(async()=>{const d=await api('/event',event);setSavedIds(old=>[...new Set([...old,d.event.id])]);setEvent(d.event);setEvents(old=>old.map(x=>x.id===d.event.id?d.event:x));setMessage('Афиша сохранена.');});}}>
 <h2>Афиша и меню</h2>{([['title','Фильм'],['date','Дата'],['time','Время'],['pricePerSeat','Базовая цена за место, ₽'],['shortDescription','Краткое описание'],['description','Описание'],['menuDescription','Описание меню']] as const).map(([field,label])=><label key={field}>{label}<input required type={field==='date'?'date':field==='time'?'time':field==='pricePerSeat'?'number':'text'} min={field==='pricePerSeat'?1:undefined} value={event[field]} onChange={e=>change(field,field==='pricePerSeat'?Number(e.target.value):e.target.value)}/></label>)}
 <fieldset className="admin-table-prices"><legend>Стоимость мест за каждым столом</legend><p>Цена за одного гостя. Для обоих мест за столом действует одна цена. Пустое поле использует базовую цену. Изменения применяются после сохранения афиши.</p><div className="table-price-inputs">{cinemaHallConfig.tables.map(table=><label key={table.id}>Стол {String(table.number).padStart(2,'0')} · ₽ за место<input type="number" min="1" max="100000" step="1" aria-label={`Цена места за столом ${table.number}`} placeholder={String(event.pricePerSeat)} value={event.tablePrices?.[table.id]??''} onChange={e=>{const value=e.target.value;setEvent(old=>{if(!old)return old;const tablePrices={...old.tablePrices};if(value==='')delete tablePrices[table.id];else tablePrices[table.id]=Number(value);return {...old,tablePrices};});}}/></label>)}</div><button type="button" disabled={busy} onClick={()=>change('tablePrices',{})}>Применить базовую цену ко всем столам</button></fieldset>
 <label>Меню — одна подача в строке: категория | блюдо<textarea required value={(event.menuCourses||[]).map(c=>c.category+' | '+c.name).join('\n')} onChange={e=>change('menuCourses',e.target.value.split('\n').map(line=>{const [category,...name]=line.split('|');return {category:category.trim(),name:name.join('|').trim()};}))}/></label>
 <label>Состояние<select value={event.status} onChange={e=>change('status',e.target.value)}><option value="active">Анонс</option><option value="finished">Прошедший</option></select></label>
 <img src={event.image} alt="Текущая афиша" className="admin-poster"/><label>Фото афиши (JPG, PNG, WebP, до 8 МБ)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;void run(async()=>{if(file.size>8000000)throw Error('Максимум 8 МБ');const r=await fetch('/api/cinema/admin/photo',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':file.type},body:file});const d=await r.json();if(!r.ok)throw Error(d.message);setEvent(old=>old?{...old,image:d.url,heroImage:d.url}:old);setMessage('Фото загружено. Нажмите «Сохранить афишу».');});}}/></label><button disabled={busy}>Сохранить афишу</button></form>
 <h2>Места и телефонные брони</h2>{pricesDirty&&<p className="cinema-error">Цены изменены в редакторе. Сначала сохраните афишу. На схеме показаны сохранённые цены.</p>}<div className="admin-hall"><CinemaHall seats={seats} selected={selected} price={savedEvent!.pricePerSeat} tablePrices={savedEvent!.tablePrices} onView={setView} locked={busy} onToggle={id=>{requestKey.current='';setSelected(old=>old.includes(id)?old.filter(s=>s!==id):[...old,id]);}}/></div><VenueView viewId={view} onClose={()=>setView(null)}/>
 <form className="customer-form" onSubmit={e=>{e.preventDefault();void run(async()=>{requestKey.current ||= crypto.randomUUID();await api('/reserve',{eventId:event.id,seatIds:selected,name,phone,expectedTotal:selectionTotal(savedEvent!,selected),requestKey:requestKey.current});requestKey.current='';setSelected([]);setName('');setPhone('');await refresh(event.id);setMessage('Бронь сохранена. Места недоступны гостям. Оплата не отмечена.');});}}><p>{selected.map(seatLabel).join('; ')||'Выберите свободные места на схеме'} · {money(selectionTotal(savedEvent!,selected))}</p><label>Имя<input required minLength={2} maxLength={80} value={name} onChange={e=>{requestKey.current='';setName(e.target.value);}}/></label><label>Телефон<input required type="tel" value={phone} onChange={e=>{requestKey.current='';setPhone(e.target.value);}}/></label><button disabled={busy||pricesDirty||!selected.length}>Сохранить бронь без оплаты</button></form>
 <h2>Список гостей</h2>{orders.map(o=><article className="admin-order" key={o.id}><strong>{o.name} · {o.phone}</strong><p>{o.seatIds.map(seatLabel).join('; ')} · {money(o.total)}</p><p>{o.status==='paid'?(o.payment.source==='admin'?'Оплачено · подтверждено администратором':'Оплачено'):o.status==='paid_review'?'Оплата получена после резерва — требуется связаться с гостем':o.status==='reserved'?'Телефонная бронь — не оплачено':'Временный резерв — ожидается оплата'}</p>{o.payment.provider==='yookassa'&&<><p>ЮKassa: {o.payment.providerId} · Чек: {o.payment.receiptStatus||'ожидается'}</p>{o.status==='paid'&&Date.now()>=Date.parse(event.startsAt)&&<button disabled={busy} onClick={()=>{if(!window.confirm('Киноужин для этого гостя состоялся и услуга оказана? Будет сформирован чек зачёта предоплаты.'))return;void run(async()=>{const result=await api('/settlement',{id:o.id});setMessage('Чек зачёта предоплаты: '+result.receipt.status+'. Повторный клик проверяет статус существующего чека.');});}}>Услуга оказана — чек зачёта / проверить статус</button>}</>}{o.payment.source==='admin'&&<p>Подтверждение: {o.payment.note}</p>}{o.status==='reserved'&&<div className="admin-toolbar"><button disabled={busy} onClick={()=>{const note=window.prompt('Укажите подтверждение оплаты: способ, дата, номер чека. Отмечайте только проверенный платёж.');if(!note)return;void run(async()=>{await api('/paid',{id:o.id,note});await refresh(event.id);setMessage('Оплата отмечена администратором.');});}}>Отметить проверенную оплату</button><button disabled={busy} onClick={()=>{if(!window.confirm('Отменить эту телефонную бронь и освободить места?'))return;void run(async()=>{await api('/cancel',{id:o.id});await refresh(event.id);});}}>Отменить бронь</button></div>}</article>)}</>}
 </main>;
}
